version: '3.8'

services:
  xai-gradio:
    build: .
    command: gradio
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped

  xai-streamlit:
    build: .
    command: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped

  xai-jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
